import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  caption!: string;
  isActive: boolean = false;
  firstName!: string;
  onChange() {
    this.isActive = !this.isActive;
    if (this.isActive) {
      this.caption = 'This message was generated by clicking the button.';
    }
  }

  onChangeInput(e: Event) {
    this.firstName = (e.target as HTMLInputElement).value;
  }
}
